import type { NextPage } from 'next'
import Head from 'next/head'
import Relog from '../components/Relog'

const Home = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div>
        <h2>box</h2>
        <Relog />
      </div>
    </div>
  )
}

export default Home
