import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useSelector } from 'react-redux'
import { RootState } from '../components/redux/store'

const Home: NextPage = () => {
  const count = useSelector((state: RootState) => state.counter.value)
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div>
        <h2>box</h2>
        <h2>{count}</h2>
      </div>
    </div>
  )
}

export default Home
